server:
  port: 8084
spring:
  security:
    oauth2:
      client:
        registration:
          google:

  datasource:
    url: jdbc:postgresql://localhost:5432/security_oauth
    username: security_oauth
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

send-mail:
  email:
    sender:
      host: smtp.outlook.com
      debug: true
      user: qwerty2345practice@outlook.com
      password: ok

